name: helm-release

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add lint values
        run: |
          printf '\nglobal:\n  deploymentId: lint\n' >> helm-charts/common/values.yaml
          printf '\nglobal:\n  deploymentId: lint\n' >> helm-charts/web-wallet/values.yaml

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: helm-charts
          branch: gh-pages
